create database BLOODBANKMANAGEMENTSYSTEM;
USE BLOODBANKMANAGEMENTSYSTEM
CREATE TABLE BLOODBANK( USR_ID INT,
BLOOD_GROUP CHAR,
PH_NO INT,
USER_NAME VARCHAR(20),
PRIMARY KEY(USR_ID));

INSERT INTO BLOODBANK VALUES(1,"O",983,"VINAYAK")
INSERT INTO BLOODBANK VALUES(2,'B',9833,'MANGALA')
INSERT INTO BLOODBANK VALUES(3,'A',971,'VASU')
INSERT INTO BLOODBANK VALUES(4,'B',953,'SHANTI')
INSERT INTO BLOODBANK VALUES(5,'o',984,'SWATI')
INSERT INTO BLOODBANK VALUES(6,'A',953,'RAMYA')

SELECT * FROM bloodbankmanagementsystem.bloodbank;

show table status;

ALTER TABLE BLOODBANKMANAGEMENTSYSTEM.BLOODBANK ADD AMOUNTOF_BLOOD INT;

UPDATE BLOODBANKMANAGEMENTSYSTEM.BLOODBANK SET AMOUNTOF_BLOOD=200 WHERE USR_ID=1;
UPDATE BLOODBANKMANAGEMENTSYSTEM.BLOODBANK SET AMOUNTOF_BLOOD=100 WHERE USR_ID=2;
UPDATE BLOODBANKMANAGEMENTSYSTEM.BLOODBANK SET AMOUNTOF_BLOOD=300 WHERE USR_ID=3;
UPDATE BLOODBANKMANAGEMENTSYSTEM.BLOODBANK SET AMOUNTOF_BLOOD=400 WHERE USR_ID=4;
UPDATE BLOODBANKMANAGEMENTSYSTEM.BLOODBANK SET AMOUNTOF_BLOOD=500 WHERE USR_ID=5;

SELECT * FROM BLOODBANK WHERE USR_ID=1;
SELECT *FROM BLOODBANK WHERE AMOUNTOF_BLOOD>300;
SELECT USR_ID FROM BLOODBANK;
SELECT * FROM BLOODBANK WHERE AMOUNTOF_BLOOD=100;

select * from BLOODBANKMANAGEMENTSYSTEM.BLOODBANK where USR_ID between 2 and 5;

SELECT COUNT(BLOOD_GROUP) from BLOODBANKMANAGEMENTSYSTEM.BLOODBANK;
SELECT AVG(AMOUNTOF_BLOOD) from BLOODBANKMANAGEMENTSYSTEM.BLOODBANK;
SELECT DISTINCT BLOOD_GROUP from BLOODBANKMANAGEMENTSYSTEM.BLOODBANK;

SELECT MAX(AMOUNTOF_BLOOD) FROM  BLOODBANKMANAGEMENTSYSTEM.BLOODBANK;

SELECT MIN(AMOUNTOF_BLOOD) FROM  BLOODBANKMANAGEMENTSYSTEM.BLOODBANK;

SELECT MAX(AMOUNTOF_BLOOD) AS MAX_AMT FROM  BLOODBANKMANAGEMENTSYSTEM.BLOODBANK;




